//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Lib.WebServicePeriodicTable {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="WebServicePeriodicTable.periodictableSoap")]
    public interface periodictableSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetAtoms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAtoms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetAtomicWeight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAtomicWeight(string ElementName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetAtomicNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAtomicNumber(string ElementName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetElementSymbol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetElementSymbol(string ElementName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface periodictableSoapChannel : R_Lib.WebServicePeriodicTable.periodictableSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class periodictableSoapClient : System.ServiceModel.ClientBase<R_Lib.WebServicePeriodicTable.periodictableSoap>, R_Lib.WebServicePeriodicTable.periodictableSoap {
        
        public periodictableSoapClient() {
        }
        
        public periodictableSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public periodictableSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public periodictableSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public periodictableSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAtoms() {
            return base.Channel.GetAtoms();
        }
        
        public string GetAtomicWeight(string ElementName) {
            return base.Channel.GetAtomicWeight(ElementName);
        }
        
        public string GetAtomicNumber(string ElementName) {
            return base.Channel.GetAtomicNumber(ElementName);
        }
        
        public string GetElementSymbol(string ElementName) {
            return base.Channel.GetElementSymbol(ElementName);
        }
    }
}
